<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ComuneSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('comuni')->delete();


        $abruzzo = array(
            array('regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Altino'),
            array('regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Archi'),
            array('regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Ari'),
            array('regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Arielli'),
            array('regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Atessa'),
            array('regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Bomba'),
            array('regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Borrello'),
            array('regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Bucchianico'),
            array('regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Canosa Sannita'),
            array('regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Carpineto Sinello'),
            array('regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Carunchio'),
            array('regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Casacanditella'),
            array('regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Casalanguida'),
            array('regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Casalbordino'),
            array('regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Casalincontrada'),
            array('regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Casoli'),
            array('regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Castel Frentano'),
            array('regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Castelguidone'),
            array('regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Castiglione Messer M'),
            array('regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Celenza sul Trigno'),
            array('regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'CHIETI'),
            array('regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Civitaluparella'),
            array('regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Civitella Messer R'),
            array('regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Colledimacine'),
            array('regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Colledimezzo'),
            array('regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Crecchio'),
            array('regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Cupello'),
            array('regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Dogliola'),
            array('regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Fallo'),
            array('regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Fara Filiorum Petri'),
            array('regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Fara San Martino'),
            array('regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Filetto'),
            array('regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Fossacesia'),
            array('regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Fraine'),
            array('regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Francavilla al Mare'),
            array('regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Fresagrandinaria'),
            array('regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Frisa'),
            array('regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Furci'),
            array('regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Gamberale'),
            array('regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Gessopalena'),
            array('regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Gissi'),
            array('regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Giuliano Teatino'),
            array('regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Guardiagrele'),
            array('regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Guilmi'),
            array('regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Lama dei Peligni'),
            array('regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Lanciano'),
            array('regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Lentella'),
            array('regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Lettopalena'),
            array('regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Liscia'),
            array('regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Miglianico'),
            array('regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Montazzoli'),
            array('regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Montebello sul Sangro'),
            array('regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Monteferrante'),
            array('regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Montelapiano'),
            array('regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Montenerodomo'),
            array('regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Monteodorisio'),
            array('regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Mozzagrogna'),
            array('regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Orsogna'),
            array('regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Ortona'),
            array('regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Paglieta'),
            array('regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Palena'),
            array('regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Palmoli'),
            array('regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Palombaro'),
            array('regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Pennadomo'),
            array('regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Pennapiedimonte'),
            array('regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Perano'),
            array('regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Pietraferrazzana'),
            array('regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Pizzoferrato'),
            array('regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Poggiofiorito'),
            array('regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Pollutri'),
            array('regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Pretoro'),
            array('regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Quadri'),
            array('regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Rapino'),
            array('regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Ripa Teatina'),
            array('regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Rocca San Giovanni'),
            array('regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Roccamontepiano'),
            array('regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Roccascalegna'),
            array('regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Roccaspinalveti'),
            array('regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Roio del Sangro'),
            array('regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Rosello'),
            array('regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'San Buono'),
            array('regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'San Giovanni Lipioni'),
            array('regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'San Giovanni Teatino'),
            array('regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'San Martino sulla M'),
            array('regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'San Salvo'),
            array('regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'San Vito Chietino'),
            array('regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Sant\'Eusanio del Sangro'),
            array('regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Santa Maria Imbaro'),
            array('regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Scerni'),
            array('regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Schiavi di Abruzzo'),
            array('regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Taranta Peligna'),
            array('regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Tollo'),
            array('regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Torino di Sangro'),
            array('regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Tornareccio'),
            array('regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Torrebruna'),
            array('regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Torrevecchia Teatina'),
            array('regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Torricella Peligna'),
            array('regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Treglio'),
            array('regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Tufillo'),
            array('regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Vacri'),
            array('regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Vasto'),
            array('regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Villa Santa Maria'),
            array('regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Villalfonsina'),
            array('regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Villamagna'),

            array('regione' =>'Abruzzo', 'provincia' =>'L\'Aquila', 'comune' => 'Acciano'),
            array('regione' =>'Abruzzo', 'provincia' =>'L\'Aquila', 'comune' => 'Aielli'),
            array('regione' =>'Abruzzo', 'provincia' =>'L\'Aquila', 'comune' => 'Alfedena'),
            array('regione' =>'Abruzzo', 'provincia' =>'L\'Aquila', 'comune' => 'Anversa degli Abruzzi'),
            array('regione' =>'Abruzzo', 'provincia' =>'L\'Aquila', 'comune' => 'Ateleta'),
            array('regione' =>'Abruzzo', 'provincia' =>'L\'Aquila', 'comune' => 'Avezzano'),
            array('regione' =>'Abruzzo', 'provincia' =>'L\'Aquila', 'comune' => 'Balsorano'),
            array('regione' =>'Abruzzo', 'provincia' =>'L\'Aquila', 'comune' => 'Barete'),
            array('regione' =>'Abruzzo', 'provincia' =>'L\'Aquila', 'comune' => 'Barisciano'),
            array('regione' =>'Abruzzo', 'provincia' =>'L\'Aquila', 'comune' => 'Barrea'),
            array('regione' =>'Abruzzo', 'provincia' =>'L\'Aquila', 'comune' => 'Bisegna'),
            array('regione' =>'Abruzzo', 'provincia' =>'L\'Aquila', 'comune' => 'Bugnara'),
            array('regione' =>'Abruzzo', 'provincia' =>'L\'Aquila', 'comune' => 'Cagnano Amiterno'),
            array('regione' =>'Abruzzo', 'provincia' =>'L\'Aquila', 'comune' => 'Calascio'),
            array('regione' =>'Abruzzo', 'provincia' =>'L\'Aquila', 'comune' => 'Campo di Giove'),
            array('regione' =>'Abruzzo', 'provincia' =>'L\'Aquila', 'comune' => 'Campotosto'),
            array('regione' =>'Abruzzo', 'provincia' =>'L\'Aquila', 'comune' => 'Canistro'),
            array('regione' =>'Abruzzo', 'provincia' =>'L\'Aquila', 'comune' => 'Cansano'),
            array('regione' =>'Abruzzo', 'provincia' =>'L\'Aquila', 'comune' => 'Capestrano'),
            array('regione' =>'Abruzzo', 'provincia' =>'L\'Aquila', 'comune' => 'Capistrello'),
            array('regione' =>'Abruzzo', 'provincia' =>'L\'Aquila', 'comune' => 'Capitignano'),
            array('regione' =>'Abruzzo', 'provincia' =>'L\'Aquila', 'comune' => 'Caporciano'),
            array('regione' =>'Abruzzo', 'provincia' =>'L\'Aquila', 'comune' => 'Cappadocia'),
            array('regione' =>'Abruzzo', 'provincia' =>'L\'Aquila', 'comune' => 'Carapelle Calvisio'),
            array('regione' =>'Abruzzo', 'provincia' =>'L\'Aquila', 'comune' => 'Carsoli'),
            array('regione' =>'Abruzzo', 'provincia' =>'L\'Aquila', 'comune' => 'Castel del Monte'),
            array('regione' =>'Abruzzo', 'provincia' =>'L\'Aquila', 'comune' => 'Castel di Ieri'),
            array('regione' =>'Abruzzo', 'provincia' =>'L\'Aquila', 'comune' => 'Castel di Sangro'),
            array('regione' =>'Abruzzo', 'provincia' =>'L\'Aquila', 'comune' => 'Castellafiume'),
            array('regione' =>'Abruzzo', 'provincia' =>'L\'Aquila', 'comune' => 'Castelvecchio Calvisio'),
            array('regione' =>'Abruzzo', 'provincia' =>'L\'Aquila', 'comune' => 'Castelvecchio Subequo'),
            array('regione' =>'Abruzzo', 'provincia' =>'L\'Aquila', 'comune' => 'Celano'),
            array('regione' =>'Abruzzo', 'provincia' =>'L\'Aquila', 'comune' => 'Cerchio'),
            array('regione' =>'Abruzzo', 'provincia' =>'L\'Aquila', 'comune' => 'Civita d\'Antino'),
            array('regione' =>'Abruzzo', 'provincia' =>'L\'Aquila', 'comune' => 'Civitella Alfedena'),
            array('regione' =>'Abruzzo', 'provincia' =>'L\'Aquila', 'comune' => 'Civitella Roveto'),
            array('regione' =>'Abruzzo', 'provincia' =>'L\'Aquila', 'comune' => 'Cocullo'),
            array('regione' =>'Abruzzo', 'provincia' =>'L\'Aquila', 'comune' => 'Collarmele'),
            array('regione' =>'Abruzzo', 'provincia' =>'L\'Aquila', 'comune' => 'Collelongo'),
            array('regione' =>'Abruzzo', 'provincia' =>'L\'Aquila', 'comune' => 'Collepietro'),
            array('regione' =>'Abruzzo', 'provincia' =>'L\'Aquila', 'comune' => 'Corfinio'),
            array('regione' =>'Abruzzo', 'provincia' =>'L\'Aquila', 'comune' => 'Fagnano Alto'),
            array('regione' =>'Abruzzo', 'provincia' =>'L\'Aquila', 'comune' => 'Fontecchio'),
            array('regione' =>'Abruzzo', 'provincia' =>'L\'Aquila', 'comune' => 'Fossa'),
            array('regione' =>'Abruzzo', 'provincia' =>'L\'Aquila', 'comune' => 'Gagliano Aterno'),
            array('regione' =>'Abruzzo', 'provincia' =>'L\'Aquila', 'comune' => 'Gioia dei Marsi'),
            array('regione' =>'Abruzzo', 'provincia' =>'L\'Aquila', 'comune' => 'Goriano Sicoli'),
            array('regione' =>'Abruzzo', 'provincia' =>'L\'Aquila', 'comune' => 'Introdacqua'),
            array('regione' =>'Abruzzo', 'provincia' =>'L\'Aquila', 'comune' => 'L\'AQUILA'),
            array('regione' =>'Abruzzo', 'provincia' =>'L\'Aquila', 'comune' => 'Lecce nei Marsi'),
            array('regione' =>'Abruzzo', 'provincia' =>'L\'Aquila', 'comune' => 'Luco dei Marsi'),
            array('regione' =>'Abruzzo', 'provincia' =>'L\'Aquila', 'comune' => 'Lucoli'),
            array('regione' =>'Abruzzo', 'provincia' =>'L\'Aquila', 'comune' => 'Magliano de\' Marsi'),
            array('regione' =>'Abruzzo', 'provincia' =>'L\'Aquila', 'comune' => 'Massa d\'Albe'),
            array('regione' =>'Abruzzo', 'provincia' =>'L\'Aquila', 'comune' => 'Molina Aterno'),
            array('regione' =>'Abruzzo', 'provincia' =>'L\'Aquila', 'comune' => 'Montereale'),
            array('regione' =>'Abruzzo', 'provincia' =>'L\'Aquila', 'comune' => 'Morino'),
            array('regione' =>'Abruzzo', 'provincia' =>'L\'Aquila', 'comune' => 'Navelli'),
            array('regione' =>'Abruzzo', 'provincia' =>'L\'Aquila', 'comune' => 'Ocre'),
            array('regione' =>'Abruzzo', 'provincia' =>'L\'Aquila', 'comune' => 'Ofena'),
            array('regione' =>'Abruzzo', 'provincia' =>'L\'Aquila', 'comune' => 'Opi'),
            array('regione' =>'Abruzzo', 'provincia' =>'L\'Aquila', 'comune' => 'Oricola'),
            array('regione' =>'Abruzzo', 'provincia' =>'L\'Aquila', 'comune' => 'Ortona dei Marsi'),
            array('regione' =>'Abruzzo', 'provincia' =>'L\'Aquila', 'comune' => 'Ortucchio'),
            array('regione' =>'Abruzzo', 'provincia' =>'L\'Aquila', 'comune' => 'Ovindoli'),
            array('regione' =>'Abruzzo', 'provincia' =>'L\'Aquila', 'comune' => 'Pacentro'),
            array('regione' =>'Abruzzo', 'provincia' =>'L\'Aquila', 'comune' => 'Pereto'),
            array('regione' =>'Abruzzo', 'provincia' =>'L\'Aquila', 'comune' => 'Pescasseroli'),
            array('regione' =>'Abruzzo', 'provincia' =>'L\'Aquila', 'comune' => 'Pescina'),
            array('regione' =>'Abruzzo', 'provincia' =>'L\'Aquila', 'comune' => 'Pescocostanzo'),
            array('regione' =>'Abruzzo', 'provincia' =>'L\'Aquila', 'comune' => 'Pettorano sul Gizio'),
            array('regione' =>'Abruzzo', 'provincia' =>'L\'Aquila', 'comune' => 'Pizzoli'),
            array('regione' =>'Abruzzo', 'provincia' =>'L\'Aquila', 'comune' => 'Poggio Picenze'),
            array('regione' =>'Abruzzo', 'provincia' =>'L\'Aquila', 'comune' => 'Prata d\'Ansidonia'),
            array('regione' =>'Abruzzo', 'provincia' =>'L\'Aquila', 'comune' => 'Pratola Peligna'),
            array('regione' =>'Abruzzo', 'provincia' =>'L\'Aquila', 'comune' => 'Prezza'),
            array('regione' =>'Abruzzo', 'provincia' =>'L\'Aquila', 'comune' => 'Raiano'),
            array('regione' =>'Abruzzo', 'provincia' =>'L\'Aquila', 'comune' => 'Rivisondoli'),
            array('regione' =>'Abruzzo', 'provincia' =>'L\'Aquila', 'comune' => 'Rocca di Botte'),
            array('regione' =>'Abruzzo', 'provincia' =>'L\'Aquila', 'comune' => 'Rocca di Cambio'),
            array('regione' =>'Abruzzo', 'provincia' =>'L\'Aquila', 'comune' => 'Rocca di Mezzo'),
            array('regione' =>'Abruzzo', 'provincia' =>'L\'Aquila', 'comune' => 'Rocca Pia'),
            array('regione' =>'Abruzzo', 'provincia' =>'L\'Aquila', 'comune' => 'Roccacasale'),
            array('regione' =>'Abruzzo', 'provincia' =>'L\'Aquila', 'comune' => 'Roccaraso'),
            array('regione' =>'Abruzzo', 'provincia' =>'L\'Aquila', 'comune' => 'San Benedetto dei Marsi'),
            array('regione' =>'Abruzzo', 'provincia' =>'L\'Aquila', 'comune' => 'San Benedetto in P'),
            array('regione' =>'Abruzzo', 'provincia' =>'L\'Aquila', 'comune' => 'San Demetrio ne\' V'),
            array('regione' =>'Abruzzo', 'provincia' =>'L\'Aquila', 'comune' => 'San Pio delle Camere'),
            array('regione' =>'Abruzzo', 'provincia' =>'L\'Aquila', 'comune' => 'San Vincenzo Valle R'),
            array('regione' =>'Abruzzo', 'provincia' =>'L\'Aquila', 'comune' => 'Sant\'Eusanio Forconese'),
            array('regione' =>'Abruzzo', 'provincia' =>'L\'Aquila', 'comune' => 'Sante Marie'),
            array('regione' =>'Abruzzo', 'provincia' =>'L\'Aquila', 'comune' => 'Santo Stefano di Sess'),
            array('regione' =>'Abruzzo', 'provincia' =>'L\'Aquila', 'comune' => 'Scanno'),
            array('regione' =>'Abruzzo', 'provincia' =>'L\'Aquila', 'comune' => 'Scontrone'),
            array('regione' =>'Abruzzo', 'provincia' =>'L\'Aquila', 'comune' => 'Scoppito'),
            array('regione' =>'Abruzzo', 'provincia' =>'L\'Aquila', 'comune' => 'Scurcola Marsicana'),
            array('regione' =>'Abruzzo', 'provincia' =>'L\'Aquila', 'comune' => 'Secinaro'),
            array('regione' =>'Abruzzo', 'provincia' =>'L\'Aquila', 'comune' => 'Sulmona'),
            array('regione' =>'Abruzzo', 'provincia' =>'L\'Aquila', 'comune' => 'Tagliacozzo'),
            array('regione' =>'Abruzzo', 'provincia' =>'L\'Aquila', 'comune' => 'Tione degli Abruzzi'),
            array('regione' =>'Abruzzo', 'provincia' =>'L\'Aquila', 'comune' => 'Tornimparte'),
            array('regione' =>'Abruzzo', 'provincia' =>'L\'Aquila', 'comune' => 'Trasacco'),
            array('regione' =>'Abruzzo', 'provincia' =>'L\'Aquila', 'comune' => 'Villa Sant\'Angelo'),
            array('regione' =>'Abruzzo', 'provincia' =>'L\'Aquila', 'comune' => 'Villa Santa Lucia dA'),
            array('regione' =>'Abruzzo', 'provincia' =>'L\'Aquila', 'comune' => 'Villalago'),
            array('regione' =>'Abruzzo', 'provincia' =>'L\'Aquila', 'comune' => 'Villavallelonga'),
            array('regione' =>'Abruzzo', 'provincia' =>'L\'Aquila', 'comune' => 'Villetta Barrea'),
            array('regione' =>'Abruzzo', 'provincia' =>'L\'Aquila', 'comune' => 'Vittorito'),

            array('regione' =>'Abruzzo', 'provincia' =>'Pescara', 'comune' => 'Abbateggio'),
            array('regione' =>'Abruzzo', 'provincia' =>'Pescara', 'comune' => 'Alanno'),
            array('regione' =>'Abruzzo', 'provincia' =>'Pescara', 'comune' => 'Bolognano'),
            array('regione' =>'Abruzzo', 'provincia' =>'Pescara', 'comune' => 'Brittoli'),
            array('regione' =>'Abruzzo', 'provincia' =>'Pescara', 'comune' => 'Bussi sul Tirino'),
            array('regione' =>'Abruzzo', 'provincia' =>'Pescara', 'comune' => 'Cappelle sul Tavo'),
            array('regione' =>'Abruzzo', 'provincia' =>'Pescara', 'comune' => 'Caramanico Terme'),
            array('regione' =>'Abruzzo', 'provincia' =>'Pescara', 'comune' => 'Carpineto della Nora'),
            array('regione' =>'Abruzzo', 'provincia' =>'Pescara', 'comune' => 'Castiglione a Casauria'),
            array('regione' =>'Abruzzo', 'provincia' =>'Pescara', 'comune' => 'Catignano'),
            array('regione' =>'Abruzzo', 'provincia' =>'Pescara', 'comune' => 'Cepagatti'),
            array('regione' =>'Abruzzo', 'provincia' =>'Pescara', 'comune' => 'Città Sant\'Angelo'),
            array('regione' =>'Abruzzo', 'provincia' =>'Pescara', 'comune' => 'Civitaquana'),
            array('regione' =>'Abruzzo', 'provincia' =>'Pescara', 'comune' => 'Civitella Casanova'),
            array('regione' =>'Abruzzo', 'provincia' =>'Pescara', 'comune' => 'Collecorvino'),
            array('regione' =>'Abruzzo', 'provincia' =>'Pescara', 'comune' => 'Corvara'),
            array('regione' =>'Abruzzo', 'provincia' =>'Pescara', 'comune' => 'Cugnoli'),
            array('regione' =>'Abruzzo', 'provincia' =>'Pescara', 'comune' => 'Elice'),
            array('regione' =>'Abruzzo', 'provincia' =>'Pescara', 'comune' => 'Farindola'),
            array('regione' =>'Abruzzo', 'provincia' =>'Pescara', 'comune' => 'Lettomanoppello'),
            array('regione' =>'Abruzzo', 'provincia' =>'Pescara', 'comune' => 'Loreto Aprutino'),
            array('regione' =>'Abruzzo', 'provincia' =>'Pescara', 'comune' => 'Manoppello'),
            array('regione' =>'Abruzzo', 'provincia' =>'Pescara', 'comune' => 'Montebello di Bertona'),
            array('regione' =>'Abruzzo', 'provincia' =>'Pescara', 'comune' => 'Montesilvano'),
            array('regione' =>'Abruzzo', 'provincia' =>'Pescara', 'comune' => 'Moscufo'),
            array('regione' =>'Abruzzo', 'provincia' =>'Pescara', 'comune' => 'Nocciano'),
            array('regione' =>'Abruzzo', 'provincia' =>'Pescara', 'comune' => 'Penne'),
            array('regione' =>'Abruzzo', 'provincia' =>'Pescara', 'comune' => 'PESCARA'),
            array('regione' =>'Abruzzo', 'provincia' =>'Pescara', 'comune' => 'Pescosansonesco'),
            array('regione' =>'Abruzzo', 'provincia' =>'Pescara', 'comune' => 'Pianella'),
            array('regione' =>'Abruzzo', 'provincia' =>'Pescara', 'comune' => 'Picciano'),
            array('regione' =>'Abruzzo', 'provincia' =>'Pescara', 'comune' => 'Pietranico'),
            array('regione' =>'Abruzzo', 'provincia' =>'Pescara', 'comune' => 'Popoli'),
            array('regione' =>'Abruzzo', 'provincia' =>'Pescara', 'comune' => 'Roccamorice'),
            array('regione' =>'Abruzzo', 'provincia' =>'Pescara', 'comune' => 'Rosciano'),
            array('regione' =>'Abruzzo', 'provincia' =>'Pescara', 'comune' => 'Salle'),
            array('regione' =>'Abruzzo', 'provincia' =>'Pescara', 'comune' => 'San Valentino in AC'),
            array('regione' =>'Abruzzo', 'provincia' =>'Pescara', 'comune' => 'Sant\'Eufemia a Maiella'),
            array('regione' =>'Abruzzo', 'provincia' =>'Pescara', 'comune' => 'Scafa'),
            array('regione' =>'Abruzzo', 'provincia' =>'Pescara', 'comune' => 'Serramonacesca'),
            array('regione' =>'Abruzzo', 'provincia' =>'Pescara', 'comune' => 'Spoltore'),
            array('regione' =>'Abruzzo', 'provincia' =>'Pescara', 'comune' => 'Tocco da Casauria'),
            array('regione' =>'Abruzzo', 'provincia' =>'Pescara', 'comune' => 'Torre de\' Passeri'),
            array('regione' =>'Abruzzo', 'provincia' =>'Pescara', 'comune' => 'Turrivalignani'),
            array('regione' =>'Abruzzo', 'provincia' =>'Pescara', 'comune' => 'Vicoli'),
            array('regione' =>'Abruzzo', 'provincia' =>'Pescara', 'comune' => 'Villa Celiera'),
                        
            array('regione' =>'Abruzzo', 'provincia' =>'Teramo', 'comune' => 'Alba Adriatica'),
            array('regione' =>'Abruzzo', 'provincia' =>'Teramo', 'comune' => 'Ancarano'),
            array('regione' =>'Abruzzo', 'provincia' =>'Teramo', 'comune' => 'Arsita'),
            array('regione' =>'Abruzzo', 'provincia' =>'Teramo', 'comune' => 'Atri'),
            array('regione' =>'Abruzzo', 'provincia' =>'Teramo', 'comune' => 'Basciano'),
            array('regione' =>'Abruzzo', 'provincia' =>'Teramo', 'comune' => 'Bellante'),
            array('regione' =>'Abruzzo', 'provincia' =>'Teramo', 'comune' => 'Bisenti'),
            array('regione' =>'Abruzzo', 'provincia' =>'Teramo', 'comune' => 'Campli'),
            array('regione' =>'Abruzzo', 'provincia' =>'Teramo', 'comune' => 'Canzano'),
            array('regione' =>'Abruzzo', 'provincia' =>'Teramo', 'comune' => 'Castel Castagna'),
            array('regione' =>'Abruzzo', 'provincia' =>'Teramo', 'comune' => 'Castellalto'),
            array('regione' =>'Abruzzo', 'provincia' =>'Teramo', 'comune' => 'Castelli'),
            array('regione' =>'Abruzzo', 'provincia' =>'Teramo', 'comune' => 'Castiglione Messer R'),
            array('regione' =>'Abruzzo', 'provincia' =>'Teramo', 'comune' => 'Castilenti'),
            array('regione' =>'Abruzzo', 'provincia' =>'Teramo', 'comune' => 'Cellino Attanasio'),
            array('regione' =>'Abruzzo', 'provincia' =>'Teramo', 'comune' => 'Cermignano'),
            array('regione' =>'Abruzzo', 'provincia' =>'Teramo', 'comune' => 'Civitella del Tronto'),
            array('regione' =>'Abruzzo', 'provincia' =>'Teramo', 'comune' => 'Colledara'),
            array('regione' =>'Abruzzo', 'provincia' =>'Teramo', 'comune' => 'Colonnella'),
            array('regione' =>'Abruzzo', 'provincia' =>'Teramo', 'comune' => 'Controguerra'),
            array('regione' =>'Abruzzo', 'provincia' =>'Teramo', 'comune' => 'Corropoli'),
            array('regione' =>'Abruzzo', 'provincia' =>'Teramo', 'comune' => 'Cortino'),
            array('regione' =>'Abruzzo', 'provincia' =>'Teramo', 'comune' => 'Crognaleto'),
            array('regione' =>'Abruzzo', 'provincia' =>'Teramo', 'comune' => 'Fano Adriano'),
            array('regione' =>'Abruzzo', 'provincia' =>'Teramo', 'comune' => 'Giulianova'),
            array('regione' =>'Abruzzo', 'provincia' =>'Teramo', 'comune' => 'Isola del Gran SDI'),
            array('regione' =>'Abruzzo', 'provincia' =>'Teramo', 'comune' => 'Martinsicuro'),
            array('regione' =>'Abruzzo', 'provincia' =>'Teramo', 'comune' => 'Montefino'),
            array('regione' =>'Abruzzo', 'provincia' =>'Teramo', 'comune' => 'Montorio al Vomano'),
            array('regione' =>'Abruzzo', 'provincia' =>'Teramo', 'comune' => 'Morro d\'Oro'),
            array('regione' =>'Abruzzo', 'provincia' =>'Teramo', 'comune' => 'Mosciano Sant\'Angelo'),
            array('regione' =>'Abruzzo', 'provincia' =>'Teramo', 'comune' => 'Nereto'),
            array('regione' =>'Abruzzo', 'provincia' =>'Teramo', 'comune' => 'Notaresco'),
            array('regione' =>'Abruzzo', 'provincia' =>'Teramo', 'comune' => 'Penna Sant\'Andrea'),
            array('regione' =>'Abruzzo', 'provincia' =>'Teramo', 'comune' => 'Pietracamela'),
            array('regione' =>'Abruzzo', 'provincia' =>'Teramo', 'comune' => 'Pineto'),
            array('regione' =>'Abruzzo', 'provincia' =>'Teramo', 'comune' => 'Rocca Santa Maria'),
            array('regione' =>'Abruzzo', 'provincia' =>'Teramo', 'comune' => 'Roseto degli Abruzzi'),
            array('regione' =>'Abruzzo', 'provincia' =>'Teramo', 'comune' => 'Sant\'Egidio alla V'),
            array('regione' =>'Abruzzo', 'provincia' =>'Teramo', 'comune' => 'Sant\'Omero'),
            array('regione' =>'Abruzzo', 'provincia' =>'Teramo', 'comune' => 'Silvi'),
            array('regione' =>'Abruzzo', 'provincia' =>'Teramo', 'comune' => 'TERAMO'),
            array('regione' =>'Abruzzo', 'provincia' =>'Teramo', 'comune' => 'Torano Nuovo'),
            array('regione' =>'Abruzzo', 'provincia' =>'Teramo', 'comune' => 'Torricella Sicura'),
            array('regione' =>'Abruzzo', 'provincia' =>'Teramo', 'comune' => 'Tortoreto'),
            array('regione' =>'Abruzzo', 'provincia' =>'Teramo', 'comune' => 'Tossicia'),
            array('regione' =>'Abruzzo', 'provincia' =>'Teramo', 'comune' => 'Valle Castellana'),
        );
        DB::table('comuni')->insert($abruzzo);


        $molise = array(
            array('regione' => 'Molise', 'provincia' => 'Campobasso', 'comune' => 'Campobasso'),
            array('regione' => 'Molise', 'provincia' => 'Campobasso', 'comune' => 'Termoli'),
            array('regione' => 'Molise', 'provincia' => 'Campobasso', 'comune' => 'Campomarino'),
            array('regione' => 'Molise', 'provincia' => 'Campobasso', 'comune' => 'Bojano'),
            array('regione' => 'Molise', 'provincia' => 'Campobasso', 'comune' => 'Larino'),
            array('regione' => 'Molise', 'provincia' => 'Campobasso', 'comune' => 'Montenero di Bisaccia'),
            array('regione' => 'Molise', 'provincia' => 'Campobasso', 'comune' => 'Guaglione'),
            array('regione' => 'Molise', 'provincia' => 'Campobasso', 'comune' => 'Riccia'),
            array('regione' => 'Molise', 'provincia' => 'Campobasso', 'comune' => 'San Martino in Pensilis'),
            array('regione' => 'Molise', 'provincia' => 'Campobasso', 'comune' => 'Trivento'),
            array('regione' => 'Molise', 'provincia' => 'Campobasso', 'comune' => 'Santa Croce di Magliano'),
            array('regione' => 'Molise', 'provincia' => 'Campobasso', 'comune' => 'Cercemaggiore'),
            array('regione' => 'Molise', 'provincia' => 'Campobasso', 'comune' => 'Petacciato'),
            array('regione' => 'Molise', 'provincia' => 'Campobasso', 'comune' => 'Vinchiaturo'),
            array('regione' => 'Molise', 'provincia' => 'Campobasso', 'comune' => 'Ferrazzano'),
            array('regione' => 'Molise', 'provincia' => 'Campobasso', 'comune' => 'Ripalimosani'),
            array('regione' => 'Molise', 'provincia' => 'Campobasso', 'comune' => 'Baranello'),
            array('regione' => 'Molise', 'provincia' => 'Campobasso', 'comune' => 'Ururi'),
            array('regione' => 'Molise', 'provincia' => 'Campobasso', 'comune' => 'Campodipietra'),
            array('regione' => 'Molise', 'provincia' => 'Campobasso', 'comune' => 'Portocannone'),
            array('regione' => 'Molise', 'provincia' => 'Campobasso', 'comune' => 'Mirabello Sannitico'),
            array('regione' => 'Molise', 'provincia' => 'Campobasso', 'comune' => 'Casacalenda'),
            array('regione' => 'Molise', 'provincia' => 'Campobasso', 'comune' => 'Sepino'),
            array('regione' => 'Molise', 'provincia' => 'Campobasso', 'comune' => 'Colletorto'),
            array('regione' => 'Molise', 'provincia' => 'Campobasso', 'comune' => 'Jelsi'),
            array('regione' => 'Molise', 'provincia' => 'Campobasso', 'comune' => 'Oratino'),
            array('regione' => 'Molise', 'provincia' => 'Campobasso', 'comune' => 'Sant\'Elia a Pianisi'),
            array('regione' => 'Molise', 'provincia' => 'Campobasso', 'comune' => 'Palata'),
            array('regione' => 'Molise', 'provincia' => 'Campobasso', 'comune' => 'San Giacomo degli Schiavi'),
            array('regione' => 'Molise', 'provincia' => 'Campobasso', 'comune' => 'Montefalcone nel Sannio'),
            array('regione' => 'Molise', 'provincia' => 'Campobasso', 'comune' => 'Gambatesa'),
            array('regione' => 'Molise', 'provincia' => 'Campobasso', 'comune' => 'Pietracatella'),
            array('regione' => 'Molise', 'provincia' => 'Campobasso', 'comune' => 'Toro'),
            array('regione' => 'Molise', 'provincia' => 'Campobasso', 'comune' => 'Castelmauro'),
            array('regione' => 'Molise', 'provincia' => 'Campobasso', 'comune' => 'Bonefro'),
            array('regione' => 'Molise', 'provincia' => 'Campobasso', 'comune' => 'Montecilfone'),
            array('regione' => 'Molise', 'provincia' => 'Campobasso', 'comune' => 'Spineto'),
            array('regione' => 'Molise', 'provincia' => 'Campobasso', 'comune' => 'Fossalto'),
            array('regione' => 'Molise', 'provincia' => 'Campobasso', 'comune' => 'Busso'),
            array('regione' => 'Molise', 'provincia' => 'Campobasso', 'comune' => 'Rotello'),
            array('regione' => 'Molise', 'provincia' => 'Campobasso', 'comune' => 'Mafalda'),
            array('regione' => 'Molise', 'provincia' => 'Campobasso', 'comune' => 'Matrice'),
            array('regione' => 'Molise', 'provincia' => 'Campobasso', 'comune' => 'Petrella Tifernina'),
            array('regione' => 'Molise', 'provincia' => 'Campobasso', 'comune' => 'Montagano'),
            array('regione' => 'Molise', 'provincia' => 'Campobasso', 'comune' => 'San Giuliano di Puglia'),
            array('regione' => 'Molise', 'provincia' => 'Campobasso', 'comune' => 'Guardialfiera'),
            array('regione' => 'Molise', 'provincia' => 'Campobasso', 'comune' => 'San Giuliano del Sannio'),
            array('regione' => 'Molise', 'provincia' => 'Campobasso', 'comune' => 'Castropignano'),
            array('regione' => 'Molise', 'provincia' => 'Campobasso', 'comune' => 'San Massimo'),
            array('regione' => 'Molise', 'provincia' => 'Campobasso', 'comune' => 'Campolieto'),
            array('regione' => 'Molise', 'provincia' => 'Campobasso', 'comune' => 'Tufara'),
            array('regione' => 'Molise', 'provincia' => 'Campobasso', 'comune' => 'Gildone'),
            array('regione' => 'Molise', 'provincia' => 'Campobasso', 'comune' => 'Colle d\'Anchise'),
            array('regione' => 'Molise', 'provincia' => 'Campobasso', 'comune' => 'Guardiaregia'),
            array('regione' => 'Molise', 'provincia' => 'Campobasso', 'comune' => 'Torella del Sannio'),
            array('regione' => 'Molise', 'provincia' => 'Campobasso', 'comune' => 'Limosano'),
            array('regione' => 'Molise', 'provincia' => 'Campobasso', 'comune' => 'Roccavivara'),
            array('regione' => 'Molise', 'provincia' => 'Campobasso', 'comune' => 'Salcito'),
            array('regione' => 'Molise', 'provincia' => 'Campobasso', 'comune' => 'Lucito'),
            array('regione' => 'Molise', 'provincia' => 'Campobasso', 'comune' => 'Cercepiccola'),
            array('regione' => 'Molise', 'provincia' => 'Campobasso', 'comune' => 'Tavenna'),
            array('regione' => 'Molise', 'provincia' => 'Campobasso', 'comune' => 'Campochiaro'),
            array('regione' => 'Molise', 'provincia' => 'Campobasso', 'comune' => 'Acquaviva Collecroce'),
            array('regione' => 'Molise', 'provincia' => 'Campobasso', 'comune' => 'San Felice del Molise'),
            array('regione' => 'Molise', 'provincia' => 'Campobasso', 'comune' => 'San Giovanni in Galdo'),
            array('regione' => 'Molise', 'provincia' => 'Campobasso', 'comune' => 'Morrone del Sannio'),
            array('regione' => 'Molise', 'provincia' => 'Campobasso', 'comune' => 'Macchia Valfortore'),
            array('regione' => 'Molise', 'provincia' => 'Campobasso', 'comune' => 'Monacilioni'),
            array('regione' => 'Molise', 'provincia' => 'Campobasso', 'comune' => 'San Polo Matese'),
            array('regione' => 'Molise', 'provincia' => 'Campobasso', 'comune' => 'Casalciprano'),
            array('regione' => 'Molise', 'provincia' => 'Campobasso', 'comune' => 'Ripabottoni'),
            array('regione' => 'Molise', 'provincia' => 'Campobasso', 'comune' => 'Castellino del Biferno'),
            array('regione' => 'Molise', 'provincia' => 'Campobasso', 'comune' => 'Lupara'),
            array('regione' => 'Molise', 'provincia' => 'Campobasso', 'comune' => 'Duronia'),
            array('regione' => 'Molise', 'provincia' => 'Campobasso', 'comune' => 'Montorio nei Frentani'),
            array('regione' => 'Molise', 'provincia' => 'Campobasso', 'comune' => 'Sant\'Angelo Limosano'),
            array('regione' => 'Molise', 'provincia' => 'Campobasso', 'comune' => 'Montelongo'),
            array('regione' => 'Molise', 'provincia' => 'Campobasso', 'comune' => 'Civitacampomarano'),
            array('regione' => 'Molise', 'provincia' => 'Campobasso', 'comune' => 'Montemitro'),
            array('regione' => 'Molise', 'provincia' => 'Campobasso', 'comune' => 'Castelbottaccio'),
            array('regione' => 'Molise', 'provincia' => 'Campobasso', 'comune' => 'Pietracupa'),
            array('regione' => 'Molise', 'provincia' => 'Campobasso', 'comune' => 'Molise'),
            array('regione' => 'Molise', 'provincia' => 'Campobasso', 'comune' => 'San Biase'),
            array('regione' => 'Molise', 'provincia' => 'Campobasso', 'comune' => 'Provvidenti'),
            array('regione' => 'Molise', 'provincia' => 'Isernia', 'comune' => 'Isernia'),
            array('regione' => 'Molise', 'provincia' => 'Isernia', 'comune' => 'Venafro'),
            array('regione' => 'Molise', 'provincia' => 'Isernia', 'comune' => 'Agnone'),
            array('regione' => 'Molise', 'provincia' => 'Isernia', 'comune' => 'Frosolone'),
            array('regione' => 'Molise', 'provincia' => 'Isernia', 'comune' => 'Montaquila'),
            array('regione' => 'Molise', 'provincia' => 'Isernia', 'comune' => 'Pozzilli'),
            array('regione' => 'Molise', 'provincia' => 'Isernia', 'comune' => 'Sesto Campano'),
            array('regione' => 'Molise', 'provincia' => 'Isernia', 'comune' => 'Monteroduni'),
            array('regione' => 'Molise', 'provincia' => 'Isernia', 'comune' => 'Fornelli'),
            array('regione' => 'Molise', 'provincia' => 'Isernia', 'comune' => 'Macchiagodena'),
            array('regione' => 'Molise', 'provincia' => 'Isernia', 'comune' => 'Castelpetroso'),
            array('regione' => 'Molise', 'provincia' => 'Isernia', 'comune' => 'Pesche'),
            array('regione' => 'Molise', 'provincia' => 'Isernia', 'comune' => 'Sant\'Agapito'),
            array('regione' => 'Molise', 'provincia' => 'Isernia', 'comune' => 'Carovilli'),
            array('regione' => 'Molise', 'provincia' => 'Isernia', 'comune' => 'Colli a Voltutno'),
            array('regione' => 'Molise', 'provincia' => 'Isernia', 'comune' => 'Cerro al Volturno'),
            array('regione' => 'Molise', 'provincia' => 'Isernia', 'comune' => 'Rocchetta a Volturno'),
            array('regione' => 'Molise', 'provincia' => 'Isernia', 'comune' => 'Carpinone'),
            array('regione' => 'Molise', 'provincia' => 'Isernia', 'comune' => 'Macchia d\'Isernia'),
            array('regione' => 'Molise', 'provincia' => 'Isernia', 'comune' => 'Rionero Sannitico'),
            array('regione' => 'Molise', 'provincia' => 'Isernia', 'comune' => 'Miranda'),
            array('regione' => 'Molise', 'provincia' => 'Isernia', 'comune' => 'Civitanova del Sannio'),
            array('regione' => 'Molise', 'provincia' => 'Isernia', 'comune' => 'Roccamandolfi'),
            array('regione' => 'Molise', 'provincia' => 'Isernia', 'comune' => 'Pescolanciano'),
            array('regione' => 'Molise', 'provincia' => 'Isernia', 'comune' => 'Capracotta	'),
            array('regione' => 'Molise', 'provincia' => 'Isernia', 'comune' => 'Cantalupo nel Sannio'),
            array('regione' => 'Molise', 'provincia' => 'Isernia', 'comune' => 'Sessano del Molise'),
            array('regione' => 'Molise', 'provincia' => 'Isernia', 'comune' => 'Santa Maria del Molise'),
            array('regione' => 'Molise', 'provincia' => 'Isernia', 'comune' => 'Bagnoli del Trigno'),
            array('regione' => 'Molise', 'provincia' => 'Isernia', 'comune' => 'Belmonte del Sannio'),
            array('regione' => 'Molise', 'provincia' => 'Isernia', 'comune' => 'Longano'),
            array('regione' => 'Molise', 'provincia' => 'Isernia', 'comune' => 'Pietrabbondante'),
            array('regione' => 'Molise', 'provincia' => 'Isernia', 'comune' => 'Forlì del Sannio'),
            array('regione' => 'Molise', 'provincia' => 'Isernia', 'comune' => 'Vastogirardi'),
            array('regione' => 'Molise', 'provincia' => 'Isernia', 'comune' => 'Poggio Sannita'),
            array('regione' => 'Molise', 'provincia' => 'Isernia', 'comune' => 'Filignano'),
            array('regione' => 'Molise', 'provincia' => 'Isernia', 'comune' => 'Scapoli'),
            array('regione' => 'Molise', 'provincia' => 'Isernia', 'comune' => 'Montenero Val Cocchiara'),
            array('regione' => 'Molise', 'provincia' => 'Isernia', 'comune' => 'Roccasicura'),
            array('regione' => 'Molise', 'provincia' => 'Isernia', 'comune' => 'Castel San Vincenzo'),
            array('regione' => 'Molise', 'provincia' => 'Isernia', 'comune' => 'San Pietro Avellana'),
            array('regione' => 'Molise', 'provincia' => 'Isernia', 'comune' => 'Pettoranello del Molise'),
            array('regione' => 'Molise', 'provincia' => 'Isernia', 'comune' => 'Acquaviva d\'Isernia'),
            array('regione' => 'Molise', 'provincia' => 'Isernia', 'comune' => 'Sant\'Angelo del Pesco'),
            array('regione' => 'Molise', 'provincia' => 'Isernia', 'comune' => 'Castel del Giudice'),
            array('regione' => 'Molise', 'provincia' => 'Isernia', 'comune' => 'Pizzone'),
            array('regione' => 'Molise', 'provincia' => 'Isernia', 'comune' => 'Sant\'Elena Sannita'),
            array('regione' => 'Molise', 'provincia' => 'Isernia', 'comune' => 'Pescopennataro'),
            array('regione' => 'Molise', 'provincia' => 'Isernia', 'comune' => 'Chiauci'),
            array('regione' => 'Molise', 'provincia' => 'Isernia', 'comune' => 'Conca Casale'),
            array('regione' => 'Molise', 'provincia' => 'Isernia', 'comune' => 'Castelpizzuto'),
            array('regione' => 'Molise', 'provincia' => 'Isernia', 'comune' => 'Castelverrino'),
        );
        DB::table('comuni')->insert($molise);
    }
}
